name: Test and build actions
on:
  pull_request:
    branches: [ 'master' ]
jobs:
  run-test-suites:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: save node_modules
        uses: actions/cache@v2
        with: 
          path: node_modules
          key: test-node_modules
      - name: install dependencies
        run: yarn
      - name: run tests
        run: yarn test
        env:
          HEROKU_TOKEN: ${{ secrets.HEROKU_TOKEN }}
          PIPELINE_ID: ${{ secrets.PIPELINE_ID }}
  build-all-actions:
    needs: run-test-suites
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: restore node_modules
        uses: actions/cache@v2
        with: 
          path: node_modules
          key: test-node_modules
      - name: build actions
        run: yarn build
      - name: commit builds
        uses: EndBug/add-and-commit@v4
        with:
          author_name: nionata
          author_email: n.ionata129@gmail.com 
          message: "Built latest actions"
          add: "*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}