name: Test all actions
on:
  pull_request:
    branches: [ 'develop', 'master' ]
jobs:
  run-test-suites:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: install dependencies
        run: yarn
      - name: Build the docker-compose test
        run: docker-compose -f docker-compose.test.yml up -d
      - name: run tests
        run: yarn test
        env:
          HEROKU_TOKEN: ${{ secrets.HEROKU_TOKEN }}
          PIPELINE_ID: ${{ secrets.PIPELINE_ID }}
          ENVIRONMENT: development
          DATABASE_URL: ${{ steps.app.outputs.database_url }}
          SCRIPT_PATH: ./scripts