name: test
on:
  pull_request:
    branches: [ 'develop', 'master' ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: run tests
        run: yarn test
        env:
          HEROKU_TOKEN: ${{ secrets.HEROKU_TOKEN }}
          PIPELINE_ID: ${{ secrets.PIPELINE_ID }}